"""empty message

Revision ID: 0ed936f10dcf
Revises: a7bb45c16302
Create Date: 2019-04-27 22:52:39.254112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed936f10dcf'
down_revision = 'a7bb45c16302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.drop_column('body')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
