"""empty message

Revision ID: 208413064373
Revises: 48adbf2a32db
Create Date: 2019-04-03 21:54:07.891157

"""
from alembic import op
import sqlalchemy as sa
from moddoc.utils import GUID


# revision identifiers, used by Alembic.
revision = '208413064373'
down_revision = '48adbf2a32db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', GUID(), nullable=False))
        batch_op.add_column(sa.Column('user_id', GUID(), nullable=False))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
