"""empty message

Revision ID: 6f82a1973f8b
Revises: 89c658215b94
Create Date: 2019-04-28 00:03:22.297213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f82a1973f8b'
down_revision = '89c658215b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('revision_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('revision_date')

    # ### end Alembic commands ###
