"""empty message

Revision ID: 8514c9a439e4
Revises: c2a9736abee2
Create Date: 2019-04-23 16:45:27.844303

"""
from alembic import op
import sqlalchemy as sa
from moddoc.utils import GUID


# revision identifiers, used by Alembic.
revision = '8514c9a439e4'
down_revision = 'c2a9736abee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository_id', GUID(), nullable=True))
        batch_op.drop_constraint('module_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('module_name_key', ['name'])
        batch_op.drop_column('repository_id')

    # ### end Alembic commands ###
