"""empty message

Revision ID: 89c658215b94
Revises: 0ed936f10dcf
Create Date: 2019-04-27 23:48:33.608441

"""
from alembic import op
import sqlalchemy as sa
from moddoc.utils import GUID


# revision identifiers, used by Alembic.
revision = '89c658215b94'
down_revision = '0ed936f10dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', GUID(), nullable=True))
        batch_op.drop_constraint('document_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', GUID(), nullable=True))
        batch_op.add_column(sa.Column('revision_data', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('revision_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('revision_name_key', ['name'])
        batch_op.drop_column('revision_data')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('document_name_key', ['name'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
