"""empty message

Revision ID: a97b0f446d2c
Revises: d54c0978cfb1
Create Date: 2019-05-15 19:31:42.834738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97b0f446d2c'
down_revision = 'd54c0978cfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('write', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.drop_column('write')

    # ### end Alembic commands ###
