"""empty message

Revision ID: d1e72cc65419
Revises: fc50a6fe6651
Create Date: 2019-05-15 19:06:20.355779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1e72cc65419'
down_revision = 'fc50a6fe6651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', postgresql.UUID(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
